/**
 * languages.ts
 * Localization dictionaries for English and Kiswahili translation arrays.
 * Developed by DEV TEK INNOVATION
 * Founder & Created by DAVID FREDRICK MDIKULA
 */

export type Language = 'en' | 'sw';

export const TRANSLATIONS = {
  en: {
    appName: "Msomi AI",
    tagline: "Academic Growth Co-Pilot",
    loading: "MSOMI AI core initializing...",
    sec_onboard: "Setting up your adaptive Academic Co-Pilot & Mentor. Let's personalize your Cognitive DNA.",
    step1_title: "1: Mambo! Tell us about yourself",
    fullname: "Full Name or Nickname",
    univ: "University / Campus",
    custom_univ: "Enter your university name",
    course: "Course / Major",
    year: "Year of Study",
    proceed_learning: "Proceed to Learning Plan",
    step2_title: "2: Cognitive DNA Setup",
    preferred_language: "Preferred Language",
    difficulty_target: "Difficulty Target",
    how_learn: "How do you learn best?",
    strengths: "What are your strengths / key hurdles?",
    career_interest: "Career Interests / Innovations you care about",
    init_msomi: "Initialize Msomi AI",
    back: "Back",
    stored_secure: "Stored securely in local workspace",
    overview_home: "Overview Home",
    mentor_hub: "Mentor Hub",
    syllabus_tracker: "Syllabus Tracker",
    study_groups: "Study Groups",
    saa_msomi: "Saa ya Msomi",
    mazoezi_drills: "Mazoezi Drills",
    innovation_lab: "Innovation Lab",
    calibrate_dna: "Calibrate DNA",
    smart_planner: "Smart Planner",
    andika_cv: "Andika CV",
    overview_title: "Dawati Kuu la Msomi (Overview Dashboard)",
    overview_subtitle: "Track syllabus progress, coordinate classmate discussions, and practice.",
    gpa_target: "GPA Target Level",
    study_mins: "Saa ya Msomi Completed",
    total_focus: "Total registered continuous focus logged",
    start_focus: "Start Focus Period",
    syllabus_progress: "Aggregated Syllabus Progress",
    inspect_courses: "Inspect Courses Track",
    active_seminars: "Active Seminar Cohorts",
    joined_cohorts_desc: "Joined study cohorts sharing nodes information",
    join_new_seminars: "Join New Seminars",
    syllabi_status_title: "Maendeleo ya Kozi (My Syllabi Status)",
    view_tracker: "View Tracker",
    exams_countdown_title: "Kikokotoo cha Mitihani (Alarms & Countdowns)",
    open_planner: "Fungua Planner",
    daily_tip: "Dondoo ya Muhula (Daily Tip)",
    tip_text: "Discussing studies with classmate cohorts inside Study Groups increases cognitive assimilation by 45% compared to studying solo. Share summary flashcards, track milestone questions, and build regional solutions here!",
    quick_actions: "Quick Actions",
    ask_tutor: "Ask Msomi AI Tutor Engine",
    start_practice: "Start Practice MCQ Exam Drill",
    map_innovation: "Map Innovation pitching blueprint",
    active_session_sync: "Active academic session synchronized on",
    calibrated_learning_style: "learning pace",
    powered_by: "Powered by DEV TEK INNOVATION",
    creator_credits: "Founder & Created by DAVID FREDRICK MDIKULA",
    login_system_title: "Secure Verification Portal",
    sign_in: "Sign In",
    sign_up: "Sign Up",
    sign_out: "Sign Out",
    email: "Email Address",
    password: "Password",
    wrong_pass: "Invalid credentials. Please attempt again.",
    no_user: "User account does not exist. Please create an account.",
    welcome_back: "Welcome style authenticated!",
    register_new_user: "Create Academic Security Profile",
    real_comm_gateway: "Interactive Professional Communications Console",
    real_comm_desc: "Configure standard SMTP Email and Telco SMS Server credentials to send physical, real-world notifications.",
    phone_number: "Phone Number",
    message_content: "Message Content",
    subject: "Subject / Alert Header",
    send_sms_btn: "Transmit Outbound SMS",
    send_email_btn: "Transmit Outbound Email",
    select_language: "Select Language",
    active_theme: "Active Theme",
    light_mode: "Light Mode",
    dark_mode: "Dark Mode",
    simulation_mode: "Simulated Delivery (Zero Cost)",
    live_production_mode: "Live Server Delivery (Real API Payload)",
    status: "Status",
    pending: "Pending",
    sent: "Sent",
    failed: "Failed",
    logs_title: "Carrier API Telemetry Logs (SMTP & Telco)",
    dns_resolving: "DNS lookup performed. Resolving standard routing gateway...",
    connection_established: "Channel TLS handshake handshake successful.",
    payload_validation: "JSON Payload structured and validated successfully.",
    transmission_triggered: "POST request fired to SMS/Email API host.",
    gate_accepted: "202 Accepted. Transaction ID allocated: MSOMI-API-",
    cost_estimation: "Message successfully queued. Estimated Cost: "
  },
  sw: {
    appName: "Msomi AI",
    tagline: "Msaidizi wa Ukuaji wa Kitaaluma",
    loading: "Uanzishaji wa mfumo wa MSOMI AI unaendelea...",
    sec_onboard: "Kuweka Msaidizi na Mentor wako wa Kitaaluma unaojiandaa. Hebu tubinafsishe DNA yako ya utambuzi.",
    step1_title: "1: Mambo! Tueleze kuhusu wewe mwenyewe",
    fullname: "Jina Kamili au la Utani",
    univ: "Chuo Kikuu / Kampasi",
    custom_univ: "Ingiza jina la chuo chako kikuu",
    course: "Kozi / Masomo Makubwa",
    year: "Mwaka wa Masomo",
    proceed_learning: "Endelea kwenye Mpango wa Kujifunza",
    step2_title: "2: Usanidi wa DNA ya Utambuzi",
    preferred_language: "Lugha Unayopendelea",
    difficulty_target: "Kiwango cha Ugumu unacholenga",
    how_learn: "Je, unajifunza vipi vizuri zaidi?",
    strengths: "Je, una uwezo gani mkubwa au changamoto zipi?",
    career_interest: "Mambo ya Kazi unayovutiwa nayo / Ubunifu unaowajali",
    init_msomi: "Anzisha Msomi AI",
    back: "Rudi Nyuma",
    stored_secure: "Imehifadhiwa kwa usalama kienyeji kwenye kivinjari",
    overview_home: "Dawati Kuu / Home",
    mentor_hub: "Kituo cha Mentor",
    syllabus_tracker: "Mfuatiliaji Silabasi",
    study_groups: "Vikundi vya Masomo",
    saa_msomi: "Saa ya Msomi",
    mazoezi_drills: "Mazoezi ya Mitihani",
    innovation_lab: "Kituo cha Ubunifu",
    calibrate_dna: "Weka Vipengele vya DNA",
    smart_planner: "Ratiba ya Kusoma",
    andika_cv: "Andika CV",
    overview_title: "Dawati Kuu la Msomi (Overview Dashboard)",
    overview_subtitle: "Fuatilia maendeleo ya silabasi, jadiliana na wasomi wenzako, na fanya mazoezi.",
    gpa_target: "Kiwango cha GPA unacholenga",
    study_mins: "Saa ya Msomi Imekamilika",
    total_focus: "Jumla ya muda wa kusoma uliorekodiwa",
    start_focus: "Anza Kipindi cha Kusoma",
    syllabus_progress: "Ujumla wa Maendeleo ya Silabasi",
    inspect_courses: "Angalia Kozi na Masomo",
    active_seminars: "Vikundi vya Masomo Vinavyofanya Kazi",
    joined_cohorts_desc: "Ulijiunga na vikundi ili kubadilishana habari",
    join_new_seminars: "Jiunge na Vikundi Vipya",
    syllabi_status_title: "Maendeleo ya Kozi (My Syllabi Status)",
    view_tracker: "Fungua tracker",
    exams_countdown_title: "Kikokotoo cha Mitihani (Alarms & Countdowns)",
    open_planner: "Fungua Planner",
    daily_tip: "Dondoo ya Leo (Daily Tip)",
    tip_text: "Kujadili masomo na wenzako kwenye Study Groups kunaongeza uelewa kwa asilimia 45% kuliko kusoma peke yako. Shiriki muhtasari wa notes na ujenge mifumo hapa chuo!",
    quick_actions: "Matendo ya Haraka",
    ask_tutor: "Uliza Akili Mnemba (Msomi AI)",
    start_practice: "Anza Mazoezi ya Mitihani",
    map_innovation: "Tengeneza mchoro wa wazo la Ubunifu",
    active_session_sync: "Kipindi cha chuo kimesawazishwa kikamilifu kwenye",
    calibrated_learning_style: "mwendo wa kujifunza",
    powered_by: "Inaendeshwa na DEV TEK INNOVATION",
    creator_credits: "Mwanzilishi & Imeundwa na DAVID FREDRICK MDIKULA",
    login_system_title: "Lango Salama la Uthibitishaji",
    sign_in: "Ingia",
    sign_up: "Sajili Akaunti",
    sign_out: "Ondoka",
    email: "Anwani ya Barua Pepe",
    password: "Nenosiri",
    wrong_pass: "Maelezo ya nenosiri au barua pepe si sahihi. Jaribu tena.",
    no_user: "Akaunti hii haipo. Tafadhali bonyeza Sajili Akaunti kuunda mpya.",
    welcome_back: "Uthibitishaji umefanikiwa kikamilifu!",
    register_new_user: "Unda Wasifu Salama wa Kitaaluma",
    real_comm_gateway: "Lango la Kijanja la Mawasiliano ya Kweli ya SMS & Barua Pepe",
    real_comm_desc: "Sanidi seva yako halisi ya SMTP Email na API ya SMS ili kutuma taarifa halisi duniani, bila data za uongo.",
    phone_number: "Namba ya Simu",
    message_content: "Maudhui ya Ujumbe",
    subject: "Kichwa cha Taarifa",
    send_sms_btn: "Tuma SMS Sasa Halisi",
    send_email_btn: "Tuma Barua Pepe Halisi",
    select_language: "Chagua Lugha",
    active_theme: "Mandhari ya Mfumo",
    light_mode: "Mwanga upeo (Light Mode)",
    dark_mode: "Giza nene (Dark Mode)",
    simulation_mode: "Mandhari ya Kijaribio (Bure kabisa)",
    live_production_mode: "Mandhari Halisi (Inatuma kwenye Seva)",
    status: "Hali",
    pending: "Inasubiri",
    sent: "Imetumwa",
    failed: "Imeshindikana",
    logs_title: "Kumbukumbu na Shughuli za Gateway (Telco & SMTP)",
    dns_resolving: "Tunatafuta anwani ya DNS. Tunatambua kivuko cha Telco...",
    connection_established: "Uunganisho wa TLS umefanikiwa kikamilifu.",
    payload_validation: "Maudhui ya ujumbe katika mfumo wa JSON yamethibitishwa vizuri.",
    transmission_triggered: "Ujumbe umerushwa kwenda kwa seva kuu ya mawasiliano.",
    gate_accepted: "202 Accepted. Namba ya kipekee ya ujumbe: MSOMI-API-",
    cost_estimation: "Ujumbe tayari upo kwenye foleni ya kutumwa. Gharama makadirio: "
  }
};
